apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image:  bitnami/mysql:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: MYSQL_DATABASE

        volumeMounts:
          - name: mysql-storage
            mountPath: "/bitnami/mysql"
          - name: init-script-volume
            mountPath: "/docker-entrypoint-initdb.d"

      volumes:  
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: my-pvc
      - name: init-script-volume
        configMap:
          name: my-config
          items:
          - key: init.sql
            path: init.sql
          

